<?php

namespace Viva\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findBy(array(), array('title'=>'asc'));
    }    
}
